### PR TITLE
add design section kind / rename section properties

### LINKED ISSUE #36: handle arbitrary section kinds
TODO from the comment on this line

https://github.com/sipb/hydrant/blob/3bad537ba0226c08d29901d9bf4110f39801b2bf/scrapers/fireroad.py#L66

Some classes' schedules are broken because Hydrant doesn't handle arbitrary section kinds. For example, 4.021 design studio's sections are called "Design." I listed out all the classes with this issue and they're all classes with "Design" sections (except for 2.00B Toy Product Design, which has the text "Labs offered: 9-12, 2-5, 7-10. Students will choose the time. That is best for their schedu."

Screen Shot 2023-03-10 at 11 47 02 PM

there are few possible fixes. We could add add a `Design` section kind, which would fix this problem for now (and probably for the forseeable future; tbh I doubt MIT classes are suddenly going to start adding many different section kinds). ofc, this wouldn't "handle arbitrary section kinds."

we could also change sections to be a map mapping the section type as a string to an `Array<RawSection>`, e.g.:

```typescript
{
  "Lab":  [[[10, 2], [70, 2]], "34-101"],
  "Design": [[[10, 2], [70, 2]], "34-101"],
  "Some other section kind": [[[10, 2], [70, 2]], "34-101"],
}
```

it seems like this would involve refactoring more of the code though. another downside(?) is the strings in the objects are longer (which I assume is the purpose of having 1-2 letter strings for all the raw class object keys?).

I'm down to do either this refactoring or the adding "Design" section kind, provided that hydrant maintainers are ok with me messing with the class data type.

### PR DESCRIPTION
**Pull request by reeceyang**
close #36

### CODE REVIEW

**Review by cjquines — COMMENTED** [review]
i guess this brings up the question of whether we can take hits to the size of `rawClass`. idk if they're served with gzip

**Comment by reeceyang** [comment]
Screen Shot 2023-03-16 at 8 50 44 PM

[latest.json ](http://hydrant.mit.edu/latest.json) has `gzip, deflate` in its headers so seems like it is. 

the current latest.json is 474 kb gzipped, and with the new names it becomes 478 kb gzipped.

**Comment by reeceyang** [comment]
we can also hold off on the renaming for now and use "e" and "er" or something for the design sections

**Review by cjquines — APPROVED** [review]
someone not me should merge

**Review by psvenk — APPROVED** [review]

**Pull request merged**
