### PR TITLE
Add exporting to .ics

### PR DESCRIPTION
**Pull request by dolphingarlic**
Temporary fix for #8 

(My code is horrible, I know)

### CODE REVIEW

**Comment by Li357** [comment]
what if there were two separate hooks for ics export and gcal export so when the domain stuff is figured out it'll be ready too? could we also combine `toICSEvents` and `toGAPIEvents`? seems like two or three small differences

**Comment by cjquines** [comment]
agreed with @Li357 that we want to have two different hooks. biggest issue is the large blocks of code commenting, and putting it on a separate hook would mean we don't have to comment out the old code.

i dont think the shared code is enough to combine them?

**Review by cjquines — CHANGES_REQUESTED** [review]
see comment

**Comment by Li357** [comment]
maybe not, was assuming that either `createEvents` from ics or `gapi.client.calendar.events.insert` would just ignore unknown/additional properties for each event from the other format. then `start`, `end` and maybe `recurrenceRule` would be a conditional

**Review by cjquines — APPROVED** [review]

**Pull request merged**
