### PR TITLE
updating high contrast and high contrast (dark) color palettes

### LINKED ISSUE #87: Issues with high contrast themes
Classic:
image

High Contrast:
image

Classic (Dark) and High Contrast (Dark):
image

Also, the "high contrast" colors aren't exactly high contrast… 18.03 and 11.001 are almost the same color here.

### PR DESCRIPTION
**Pull request by sarahjohn1**
This pull request would close #87 

Updated the color palettes for both high contrast and high contrast (dark). From the re

1.  Original High Contrast Dark
Screenshot 2024-12-04 at 3 39 45 PM

2. Classic Dark (for reference, was not edited)
Screenshot 2024-12-04 at 3 46 47 PM

2. **Updated** High Contrast Dark
Screenshot 2024-12-04 at 3 40 31 PM

4. Original High Contrast
Screenshot 2024-12-04 at 3 41 02 PM

5. **Updated** High Contrast
Screenshot 2024-12-04 at 3 41 31 PM

### CODE REVIEW

**Review by cjquines — APPROVED** [review]
lgtm.

i wonder if we can have a build step that ensures high contrast colors are wcag aaa?

**Review by psvenk — CHANGES_REQUESTED** [review]
Thanks for the PR; these colors have much better foreground/background contrast than what we have currently. I just have a few questions:
- Could we make the purple (`#BA68C8`) a little lighter so that it [passes WCAG AAA](https://webaim.org/resources/contrastchecker/)?
- The blues (`#4FC3F7` and `#64B5F6`) are very similar to each other, as are the red and the pink (`#FF6B6B` and `#FF80A4`) to a lesser extent. Would it be possible to make them more distinct while keeping them distinct from the other colors and compliant with WCAG AAA?

**Comment by sarahjohn1** [comment]
Yes of course, here are updated values and wcag contrast checkers, sorry I didn't think of this earlier! Values are updated and here are screenshots to accompany.
Screenshot 2024-12-08 at 1 07 55 AM
Screenshot 2024-12-08 at 1 13 37 AM
Screenshot 2024-12-08 at 1 13 59 AM
Screenshot 2024-12-08 at 1 16 20 AM
Screenshot 2024-12-08 at 1 16 41 AM

**Comment by psvenk** [comment]
Looks good to me; thank you! I think this is ready to merge once `highContrastDark` is also updated accordingly.

**Review by psvenk — APPROVED** [review]

**Pull request merged**
